---
# =============================================================================
# KOMODO INVENTORY - SINGLE SOURCE OF TRUTH
# =============================================================================
# All configuration centralized in this file for maximum simplicity

all:
  vars:
    # Network & Connection Settings
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

    # Komodo Core Settings
    komodo_install_dir: "/opt/komodo"
    komodo_port: 9120
    komodo_mongo_port: 27017
    komodo_mongo_cache_size_gb: 2

    # Komodo Periphery Settings
    komodo_periphery_port: 8120
    komodo_periphery_version: "latest"
    komodo_user: "komodo"
    komodo_group: "komodo"
    komodo_bind_ip: "0.0.0.0"
    komodo_bind_port: "{{ komodo_periphery_port }}"
    komodo_allowed_ips: []
    komodo_secrets: []
    komodo_periphery_root_directory: "/etc/komodo"
    enable_server_management: true

    # Computed URLs
    komodo_core_url: "http://{{ hostvars[groups['core'][0]]['ansible_host'] }}:{{ komodo_port }}"
    komodo_periphery_url_pattern: "https://{host}:{{ komodo_periphery_port }}"

    # Authentication Settings
    komodo_auth_base_url: "{{ komodo_core_url }}"
    komodo_auth_admin_username: "{{ lookup('community.general.onepassword', 'Komodo', field='username', vault='Homelab Ansible') }}"
    komodo_auth_admin_password: "{{ lookup('community.general.onepassword', 'Komodo', field='password', vault='Homelab Ansible') }}"
    komodo_auth_service_user: "komodo-automation"
    komodo_auth_service_user_description: "Service user for automated deployments and API access"
    komodo_auth_api_key_name: "deployment-api-key"

    # API Credentials (1Password lookups)
    komodo_core_api_key: "{{ lookup('community.general.onepassword', 'Komodo', field='komodo_api_key', vault='Homelab Ansible') }}"
    komodo_core_api_secret: "{{ lookup('community.general.onepassword', 'Komodo', field='komodo_api_secret', vault='Homelab Ansible') }}"

    # komodo-op Configuration (Secret Management)
    enable_komodo_op: true  # Set to true to enable komodo-op deployment
    # NOTE: komodo-op repository is now defined in komodo-resource-syncs, not here

    # Resource Syncs Configuration (GitOps)
    komodo_resource_syncs_repo: "brumi1024/komodo-resource-syncs"
    komodo_resource_syncs_branch: "main"
    komodo_resource_syncs_git_account: "brumi1024"

    # Application Stacks Configuration
    app_stacks_repo: "brumi1024/homelab-komodo-stacks"
    app_stacks_branch: "main"
    app_stacks_git_account: "brumi1024"

  children:
    # Control machine (not managed by infrastructure playbooks)
    control:
      hosts:
        localhost:
          ansible_connection: local

    # Managed Komodo infrastructure
    komodo:
      vars:
        # Parse-time variable needed for ansible_host resolution
        tailnet: "{{ lookup('community.general.onepassword', 'Network', field='tailnet', vault='Homelab Ansible') }}"
      children:
        core:
          hosts:
            docker-home:
              ansible_host: "docker-home.{{ tailnet }}"
              node_site: home
              komodo_role: core

        periphery:
          hosts:
            docker-home:
              ansible_host: "docker-home.{{ tailnet }}"
              node_site: home
              # Same-host periphery configuration
              server_address: "https://host.docker.internal:{{ komodo_periphery_port }}"

            docker-seq:
              ansible_host: "docker-seq.{{ tailnet }}"
              node_site: sequoia
              # Remote periphery with auto-generated passkey
              generate_server_passkey: true
              # Use Tailnet hostname for reliable cross-site connectivity
              server_address: "https://{{ ansible_host }}:{{ komodo_periphery_port }}"
            
            sequoia-rpi4:
              ansible_host: "sequoia-rpi4.{{ tailnet }}"
              node_site: sequoia
              # Remote periphery with auto-generated passkey
              generate_server_passkey: true
              # Use Tailnet hostname for reliable cross-site connectivity
              server_address: "https://{{ ansible_host }}:{{ komodo_periphery_port }}"

            homelab-vps:
              ansible_host: "homelab-vps.{{ tailnet }}"
              node_site: vps
              # Remote periphery with auto-generated passkey
              generate_server_passkey: true
              # Use Tailnet hostname for reliable cross-site connectivity
              server_address: "https://{{ ansible_host }}:{{ komodo_periphery_port }}"


