---
- name: Create temporary compose override to enable registration
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/temp-compose-override.yml.j2"
    dest: "{{ komodo_install_dir }}/docker-compose.override.yml"
    mode: "0644"
  delegate_to: "{{ groups['core'][0] }}"

- name: Restart Komodo Core with registration enabled
  community.docker.docker_compose_v2:
    project_src: "{{ komodo_install_dir }}"
    project_name: "komodo-core"
    state: restarted
    services:
      - core
  delegate_to: "{{ groups['core'][0] }}"

- name: Wait for Komodo Core to be ready after restart
  ansible.builtin.uri:
    url: "{{ komodo_auth_base_url }}"
    method: GET
    status_code: 200
  retries: 15
  delay: 5

- name: Create admin user
  ansible.builtin.uri:
    url: "{{ komodo_auth_base_url }}/auth"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      type: "SignUpLocalUser"
      params:
        username: "{{ komodo_auth_admin_username }}"
        password: "{{ komodo_auth_admin_password }}"
    status_code: [200, 201]
  register: komodo_auth_create_user_response
  no_log: true

- name: Remove temporary compose override
  ansible.builtin.file:
    path: "{{ komodo_install_dir }}/docker-compose.override.yml"
    state: absent
  delegate_to: "{{ groups['core'][0] }}"

- name: Restart Komodo Core to re-enable registration protection
  community.docker.docker_compose_v2:
    project_src: "{{ komodo_install_dir }}"
    project_name: "komodo-core"
    state: restarted
    services:
      - core
  delegate_to: "{{ groups['core'][0] }}"

- name: Wait for Komodo Core to be ready after final restart
  ansible.builtin.uri:
    url: "{{ komodo_auth_base_url }}"
    method: GET
    status_code: 200
  retries: 15
  delay: 5
