---
- name: Create API key for service user
  ansible.builtin.uri:
    url: "{{ komodo_auth_base_url }}/write"
    method: POST
    headers:
      Authorization: "{{ komodo_auth_jwt_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      type: "CreateApiKeyForServiceUser"
      params:
        user_id: "{{ komodo_auth_service_user_id }}"
        name: "{{ komodo_auth_api_key_name }}"
        expires: 0 # Never expires
    status_code: [200, 201]
  register: komodo_auth_api_key_response

- name: Extract API credentials
  ansible.builtin.set_fact:
    komodo_auth_api_key: "{{ komodo_auth_api_key_response.json.key }}"
    komodo_auth_api_secret: "{{ komodo_auth_api_key_response.json.secret }}"
  no_log: true
