---
- name: Update API key in 1Password
  ansible.builtin.shell: op item edit "Komodo" --vault "Homelab Ansible" "komodo_api_key={{ komodo_auth_api_key }}" < /dev/null
  no_log: true
  changed_when: true

- name: Update API secret in 1Password
  ansible.builtin.shell: op item edit "Komodo" --vault "Homelab Ansible" "komodo_api_secret={{ komodo_auth_api_secret }}" < /dev/null
  no_log: true
  changed_when: true

- name: Verify API keys were stored
  ansible.builtin.command: op item get "Komodo" --vault "Homelab Ansible" --fields komodo_api_key
  register: komodo_auth_verify_api_key
  changed_when: false
  no_log: true
