---
- name: Install Docker on Infrastructure Nodes
  hosts: komodo
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check if Docker installation is already complete
      ansible.builtin.stat:
        path: /opt/.docker_install_complete
      register: docker_marker

    - name: Skip already configured nodes
      ansible.builtin.meta: end_host
      when: docker_marker.stat.exists

    - name: Display node information
      ansible.builtin.debug:
        msg:
          - "Installing Docker on: {{ inventory_hostname }}"
          - "Site: {{ node_site }}"
          - "Ansible host: {{ ansible_host }}"

  roles:
    # Install Docker using geerlingguy's community role
    - role: geerlingguy.docker
      vars:
        docker_edition: "ce"
        docker_install_compose_plugin: true
        docker_users:
          - "{{ ansible_user }}"
        docker_daemon_options:
          log-driver: "local"
          log-opts:
            max-size: "10m"
            max-file: "3"
          storage-driver: "overlay2"
          features:
            buildkit: true
      tags: [docker]

  tasks:
    - name: Create Docker installation completion marker
      ansible.builtin.file:
        path: /opt/.docker_install_complete
        state: touch
        mode: "0644"

    - name: Display completion message
      ansible.builtin.debug:
        msg: "🐳 Docker installation completed on {{ inventory_hostname }}"
