---
- name: Deploy Komodo Core Infrastructure
  hosts: core
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check if Docker is installed
      ansible.builtin.stat:
        path: /opt/.docker_install_complete
      register: docker_marker

    - name: Fail if Docker not installed
      ansible.builtin.fail:
        msg: "Docker not installed. Run 01_docker.yml first."
      when: not docker_marker.stat.exists

    - name: Display deployment information
      ansible.builtin.debug:
        msg:
          - "Deploying Komodo Core on: {{ inventory_hostname }}"
          - "Site: {{ node_site }}"

  tasks:
    - name: Deploy Komodo Core (MongoDB + Core)
      ansible.builtin.include_role:
        name: komodo
      tags: [komodo]

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg:
          - "🦎 Komodo Core deployment complete!"
          - "Web UI available at: http://{{ ansible_host }}:{{ komodo_port }}"
          - ""
          - "✅ Ready for authentication setup!"
