---
- name: Manage Komodo Periphery Instances
  hosts: periphery
  become: true
  gather_facts: true
  serial: 2 # Deploy 2 nodes at a time to avoid overwhelming the core

  pre_tasks:
    - name: Check if Docker is installed
      ansible.builtin.stat:
        path: /opt/.docker_install_complete
      register: docker_marker

    - name: Fail if Docker not installed
      ansible.builtin.fail:
        msg: "Docker not installed. Run 01_docker.yml first."
      when: not docker_marker.stat.exists

    - name: Display action information
      ansible.builtin.debug:
        msg:
          - "Action: {{ komodo_action | default('install') }} Komodo Periphery on: {{ inventory_hostname }}"
          - "Site: {{ node_site }}"
          - "Stacks: {{ node_stacks | default([]) | join(', ') }}"

  roles:
    - role: bpbradley.komodo
      vars:
        komodo_action: install
        komodo_version: "{{ komodo_periphery_version | default('latest') }}"
      tags: [komodo-periphery]

  post_tasks:
    - name: Display completion message (install/update)
      ansible.builtin.debug:
        msg:
          - "🔗 Komodo Periphery {{ komodo_action | default('install') }}ed on {{ inventory_hostname }}"
          - "Stacks: {{ node_stacks | default([]) | join(', ') }}"
          - ""
          - "Periphery is now registered with Komodo Core and ready for deployments!"
      when: komodo_action | default('install') in ['install', 'update']

    - name: Display completion message (uninstall)
      ansible.builtin.debug:
        msg:
          - "🗑️ Komodo Periphery removed from {{ inventory_hostname }}"
          - "The systemd service and configuration have been cleaned up."
      when: komodo_action | default('install') == 'uninstall'
