---
# Trigger Application Stacks Sync
# This playbook triggers the komodo-app-stacks sync to ensure applications are synced after deployment
# Run this after komodo-op deployment to sync application stacks from the repository

- name: Trigger Application Stacks Sync
  hosts: localhost
  gather_facts: false
  vars:
    komodo_port: "{{ hostvars[groups['core'][0]]['komodo_port'] }}"
    komodo_base_url: "http://{{ hostvars[groups['core'][0]]['ansible_host'] }}:{{ komodo_port }}"
    komodo_api_key: "{{ lookup('community.general.onepassword', 'Komodo', field='komodo_api_key', vault='Homelab Ansible') }}"
    komodo_api_secret: "{{ lookup('community.general.onepassword', 'Komodo', field='komodo_api_secret', vault='Homelab Ansible') }}"

  tasks:
    - name: Trigger application stacks sync
      ansible.builtin.uri:
        url: "{{ komodo_base_url }}/execute"
        method: POST
        headers:
          X-Api-Key: "{{ komodo_api_key }}"
          X-Api-Secret: "{{ komodo_api_secret }}"
          Content-Type: "application/json"
        body_format: json
        body:
          type: "RunSync"
          params:
            sync: "komodo-app-stacks"
        status_code: [200, 201]
      register: app_sync_trigger_result

    - name: Wait for application sync completion
      ansible.builtin.uri:
        url: "{{ komodo_base_url }}/read"
        method: POST
        headers:
          X-Api-Key: "{{ komodo_api_key }}"
          X-Api-Secret: "{{ komodo_api_secret }}"
          Content-Type: "application/json"
        body_format: json
        body:
          type: "GetResourceSync"
          params:
            sync: "komodo-app-stacks"
        status_code: 200
      register: app_sync_status
      until: app_sync_status.json.info.pending_error is none or app_sync_status.json.info.pending_error == ""
      retries: 30
      delay: 10
      failed_when: app_sync_status.json.info.pending_error is not none and app_sync_status.json.info.pending_error != ""

    - name: Display completion summary
      ansible.builtin.debug:
        msg: |-
          🎉 Application Stacks Sync Complete!

          ✅ Application stacks have been synced from the repository.

          Next Steps:
          1. Check the Komodo UI for available application stacks
          2. Deploy applications manually as needed
          3. Applications are configured for manual deployment for safety
