---
- name: Deploy Komodo Periphery Instances
  hosts: komodo_periphery
  become: yes
  gather_facts: yes
  serial: 2  # Deploy 2 nodes at a time to avoid overwhelming the core

  pre_tasks:
    - name: Check if node is bootstrapped
      stat:
        path: /opt/.bootstrap_complete
      register: bootstrap_marker
      
    - name: Fail if node not bootstrapped
      fail:
        msg: "Node not bootstrapped. Run bootstrap.yml first."
      when: not bootstrap_marker.stat.exists
      
    - name: Display deployment information
      debug:
        msg: 
          - "Deploying Komodo Periphery on: {{ inventory_hostname }}"
          - "Site: {{ node_site }}"
          - "Stacks: {{ node_stacks | default([]) | join(', ') }}"
      
    - name: Wait for Komodo Core to be available
      uri:
        url: "http://{{ hostvars[groups['komodo_core'][0]]['ansible_host'] }}:9120/health"
        method: GET
      retries: 30
      delay: 10
      register: core_health
      until: core_health.status == 200
      delegate_to: localhost

    - name: Retrieve API credentials from 1Password
      set_fact:
        komodo_api_key: "{{ lookup('community.general.onepassword', 'Komodo', field='komodo_api_key', vault='Homelab') }}"
        komodo_api_secret: "{{ lookup('community.general.onepassword', 'Komodo', field='komodo_api_secret', vault='Homelab') }}"
      delegate_to: localhost
      run_once: true

    - name: Verify API credentials are available
      fail:
        msg: |
          API credentials not found in 1Password.
          Please ensure you have:
          1. Generated API keys in Komodo Core UI
          2. Stored them in 1Password item 'Komodo' in 'Homelab' vault
          3. Fields: 'komodo_api_key' and 'komodo_api_secret'
          4. Authenticated to 1Password CLI: 'op signin'
      when: komodo_api_key == "" or komodo_api_secret == ""

  roles:
    # Deploy Komodo Periphery using bpbradley's systemd-based role
    - role: bpbradley.komodo
      vars:
        komodo_action: "install"
        komodo_version: "{{ komodo_periphery_version | default('latest') }}"
        komodo_core_url: "http://{{ hostvars[groups['komodo_core'][0]]['ansible_host'] }}:9120"
        generate_server_passkey: true  # Auto-generate passkey and register with Komodo Core
        komodo_api_key: "{{ komodo_api_key }}"
        komodo_api_secret: "{{ komodo_api_secret }}"
        komodo_secrets: "{{ komodo_periphery_secrets | default([]) }}"
      tags: [komodo-periphery]

  post_tasks:
    - name: Display completion message
      debug:
        msg: 
          - "🔗 Komodo Periphery deployed on {{ inventory_hostname }}"
          - "Stacks: {{ node_stacks | default([]) | join(', ') }}"
          - ""
          - "Periphery is now registered with Komodo Core and ready for deployments!"