---
# Check status of Komodo services
# This playbook replaces hardcoded values in Makefile with proper variables

- name: Check Komodo Core status
  hosts: core
  gather_facts: false
  tasks:
    - name: Check Komodo Core health endpoint
      ansible.builtin.uri:
        url: "http://localhost:{{ komodo_port }}"
        method: GET
        status_code: 200
        timeout: 5
      register: core_health
      failed_when: false

    - name: Display Core status
      ansible.builtin.debug:
        msg: "{{ '✅ Komodo Core is healthy' if core_health.status == 200 else '❌ Komodo Core is not responding' }}"

    - name: Check Core Docker containers
      ansible.builtin.command: docker ps --filter 'name=komodo-core' --format 'table {{ "{{.Names}}" }}\t{{ "{{.Status}}" }}'
      register: core_containers
      changed_when: false
      failed_when: false

    - name: Display Core containers
      ansible.builtin.debug:
        msg: "{{ core_containers.stdout_lines if core_containers.rc == 0 else 'Could not check Core containers' }}"

- name: Check Komodo Periphery status
  hosts: periphery
  gather_facts: false
  pre_tasks:
    - name: Set runtime variables for parse-time requirements
      ansible.builtin.set_fact:
        _komodo_user: "{{ komodo_user }}"
  tasks:
    - name: Check Periphery systemd service status
      ansible.builtin.systemd:
        name: periphery
        scope: user
      become: true
      become_user: "{{ _komodo_user }}"
      register: periphery_status
      failed_when: false

    - name: Display Periphery status
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: {{ '✅ Running' if periphery_status.status.ActiveState == 'active' else '❌ Not running' }}"

- name: Status Summary
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display summary
      ansible.builtin.debug:
        msg:
          - "🔍 Komodo Infrastructure Status Check Complete"
          - ""
          - "Core servers: {{ groups['core'] | length }}"
          - "Periphery nodes: {{ groups['periphery'] | length }}"
          - ""
          - "For detailed logs:"
          - "  Core: docker logs komodo-core-komodo-1"
          - "  Periphery: sudo -u komodo journalctl --user -u periphery -f"
