---
# Komodo Core Health Check - Reusable across playbooks
# This task checks if Komodo Core is responding and healthy

- name: Check Komodo Core health
  ansible.builtin.uri:
    url: "{{ komodo_base_url }}"
    method: GET
    status_code: 200
  retries: 5
  delay: 10
  tags: [api, health_check]
