---
# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
    branches: [main, IaC]
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-lint.yml'
      - '.ansible-lint'
  pull_request:
    branches: [main]
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible-lint.yml'
      - '.ansible-lint'
jobs:
  build:
    name: Ansible Lint  # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: "ansible/"